settings:

  general:
    test: true

  preferences:
    color_mode: "light"

  timetable:
    host: "192.168.178.23"
    port: "5400"
    database: "school"
    user: "postgres"
    password: "delta1"

  language: "English"
